"""initial-schema

Revision ID: 356403278d76
Revises: 
Create Date: 2026-05-29 23:41:32.524799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356403278d76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('memory_scope', sa.String(length=64), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('local_first_privacy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'agent_id', name='uq_workspace_agent')
    )
    with op.batch_alter_table('workspace_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_agents_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_agents_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('consolidation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consolidation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consolidation_jobs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consolidation_jobs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consolidation_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_consolidation_jobs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('memory_type', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('pending_approval', sa.Boolean(), nullable=False),
    sa.Column('storage_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['source_session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('workspace_id', 'content_hash', name='uq_memory_workspace_content_hash')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_embedding_hash'), ['embedding_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_memory_type'), ['memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_sensitivity_level'), ['sensitivity_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_source_session_id'), ['source_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_visibility'), ['visibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_memory_scope', ['workspace_id', 'agent_id', 'memory_type', 'archived', 'deleted_at'], unique=False)

    op.create_table('session_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_messages_session_id'), ['session_id'], unique=False)

    op.create_table('memory_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_access_logs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_access_logs_memory_id'), ['memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_access_logs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('memory_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('embedding_hash', sa.String(length=64), nullable=False),
    sa.Column('vector_dim', sa.Integer(), nullable=False),
    sa.Column('faiss_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id')
    )
    with op.batch_alter_table('memory_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_embeddings_embedding_hash'), ['embedding_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_embeddings_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('vision_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('snapshot_path', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('saved_as_memory_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['saved_as_memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vision_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_events_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_events_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vision_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_events_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_vision_events_agent_id'))

    op.drop_table('vision_events')
    with op.batch_alter_table('memory_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_embeddings_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_memory_embeddings_embedding_hash'))

    op.drop_table('memory_embeddings')
    with op.batch_alter_table('memory_access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_access_logs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_memory_access_logs_memory_id'))
        batch_op.drop_index(batch_op.f('ix_memory_access_logs_agent_id'))

    op.drop_table('memory_access_logs')
    with op.batch_alter_table('session_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_messages_session_id'))

    op.drop_table('session_messages')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_scope')
        batch_op.drop_index(batch_op.f('ix_memories_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_memories_visibility'))
        batch_op.drop_index(batch_op.f('ix_memories_source_session_id'))
        batch_op.drop_index(batch_op.f('ix_memories_session_id'))
        batch_op.drop_index(batch_op.f('ix_memories_sensitivity_level'))
        batch_op.drop_index(batch_op.f('ix_memories_memory_type'))
        batch_op.drop_index(batch_op.f('ix_memories_expires_at'))
        batch_op.drop_index(batch_op.f('ix_memories_embedding_hash'))
        batch_op.drop_index(batch_op.f('ix_memories_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_memories_created_at'))
        batch_op.drop_index(batch_op.f('ix_memories_content_hash'))
        batch_op.drop_index(batch_op.f('ix_memories_archived'))
        batch_op.drop_index(batch_op.f('ix_memories_agent_id'))

    op.drop_table('memories')
    with op.batch_alter_table('consolidation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consolidation_jobs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_consolidation_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_consolidation_jobs_session_id'))
        batch_op.drop_index(batch_op.f('ix_consolidation_jobs_agent_id'))

    op.drop_table('consolidation_jobs')
    with op.batch_alter_table('workspace_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_agents_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_agents_agent_id'))

    op.drop_table('workspace_agents')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_sessions_agent_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_agent_id'))

    op.drop_table('api_keys')
    op.drop_table('workspaces')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))

    op.drop_table('app_settings')
    op.drop_table('agents')
    # ### end Alembic commands ###
