"""initial schema

Revision ID: e11602352b13
Revises: f6a7b8c9d0e1
Create Date: 2026-06-03 08:47:54.647089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11602352b13'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_vectors', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_vectors_memory_id')
        batch_op.create_index(batch_op.f('ix_memory_vectors_memory_id'), ['memory_id'], unique=True)
        batch_op.drop_index('ix_memory_vectors_vector_id')
        batch_op.create_index(batch_op.f('ix_memory_vectors_vector_id'), ['vector_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_vectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_vectors_vector_id'))
        batch_op.create_index('ix_memory_vectors_vector_id', ['vector_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_memory_vectors_memory_id'))
        batch_op.create_index('ix_memory_vectors_memory_id', ['memory_id'], unique=False)

    # ### end Alembic commands ###
